# Главный исполняемый файл (по умолчанию: "main.py")
main_file: main.py

# Режим запуска:
# "once" — запуск один раз
# "loop" — запуск в цикле во втором потоке
# (по умолчанию: "once")
launch_mode: once

# Название главной функции (по умолчанию: "mainloop")
main_function: mainloop

#Уникальный ID модуля | У двух модулей не может быть один и тот же ID
ID: 123456789
